#!/bin/sh /etc/rc.common
# Copyright (C) 2014 OpenWrt.org

USE_PROCD=1
START=98
STOP=102
PROG=/bin/ifmon

start_service()
{
        procd_open_instance
        procd_set_param command $PROG
        procd_set_param respawn
        procd_close_instance
}

#start_service() {
#	ifmon &
#}

#stop_service() {
#	killall -9 ifmon
#}
