#!/bin/sh /etc/rc.common

START=30
STOP=85
USE_PROCD=1


PROG=/sbin/nbns

start_service() {
        killall  nbns
	if [ "$1" = "" -o "$2" = "" ]
	then
		return
	fi 
        procd_open_instance
        procd_set_param command "$PROG" -i "$1" -s "$2"
        procd_set_param respawn
        procd_close_instance
}
