#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=50
USE_PROCD=1

validate_qos_section()
{
	uci_validate_section qos interface "${1}" \
		'enabled:bool' \
		'upload:uinteger' \
		'download:uinteger'
}

service_triggers()
{
    local enable  
	local mode
    mode=`uci get network.globals.network_mode`
	
	procd_add_reload_trigger "qos"
	procd_add_validation validate_qos_section
	enable=`uci -q get qos.wan.enabled`                      
	if [ $enable != 0 ];then                                 
		if [ "$mode" != "bridge" -a "$mode" != "repeater" ]
		then
			qos-start                                                
		fi                                                
	fi                                                       
}

start_service() {
    local enable 
	local mode
    mode=`uci get network.globals.network_mode`		
	enable=`uci -q get qos.wan.enabled`                      
	if [ $enable != 0 ];then                                 
		if [ "$mode" != "bridge" -a "$mode" != "repeater" ]
		then
			qos-start                                                
		fi                                                 
	fi                                                       
}                                                                

reload_service() {
    local enable  
	local mode
    mode=`uci get network.globals.network_mode`		
	enable=`uci -q get qos.wan.enabled`                      
	if [ $enable != 0 ];then                                 
		if [ "$mode" != "bridge" -a "$mode" != "repeater" ]
		then
			qos-start                                                
		fi                                                 
	fi                                                       
}

stop_service() {
	qos-stop
}

