#!/bin/sh /etc/rc.common
# Copyright (C) 2014 OpenWrt.org

USE_PROCD=1
START=99
STOP=102

start_service1()
{
        procd_open_instance
        procd_set_param command "/bin/stad"
        procd_append_param command 1
        procd_set_param respawn
        procd_close_instance
}

start_service2()
{
        procd_open_instance
        procd_set_param command "/bin/stad"
        procd_append_param command 2
        procd_set_param respawn
        procd_close_instance
}

start_service() {
	mode=`uci get network.globals.network_mode`
	if [ -z "${mode}" -o "${mode}" = router ];then
		start_service1
		start_service2
	fi
#	stad 1&
#       stad 2&
}

#stop_service() {
#	killall -9 stad
#}
